import Layout from 'components/BlogPostLayout';

export default ({ children }) => <Layout title={meta.title}>{children}</Layout>;

export const meta = {
    postNumber: 3,
    title: 'Giving Birth',
    author: 'Kadi Hill',
    pubDate: 'February 5th, 2019',
    tags: [],
    description:
        'At 35 weeks pregnant I was sleeping in a camping hammock on a very beautiful, yet very primitive island.',
};

At 35 weeks pregnant I was sleeping in a camping hammock on a very beautiful, yet very primitive island in San Blas, Panama unsure of where I was actually going to birth my baby.The islands are an autonomously run reservation of the Guna Indians, an indigenous people of Panama.We first visited these islands on our honeymoon and spent two months with the Guna.The time we spent there with them inspired my husband and I to have children.

They inspired us so much, that when we got pregnant with our first child, we gave up familiarity and security, having friends and family around during one of life's most vulnerable times, creature comforts like my own bathroom and running water in exchange for knowledge. How did they raise these perfectly content and capable children and how were both Mother and Baby so happy and supported? I had to know.

This was a chance to see what motherhood and parenthood and humanity look like in an intact village.To see the beauty of postpartum care and what a supported mother of a newborn looks like.A mother who has sisters and aunties and her own mother around her caring for her baby and for her as she cares for her baby.A mother who spends her whole day tending to baby's every need, including every time baby needs to potty because baby is likely not wearing a diaper, or if so just a thin cloth one while also continuing her hobbies at leisure and participating in running the house. These mamas looked well rested and refreshed and happy swinging their content babies with them in the hammock all day as they sat around surrounded by the closest women in their life. I wanted to know everything there was to know about this, as opposed to the strung out, isolated, overworked, exhausted mom with soggy cheerios in her hair who just wanted to sit alone in the car for 5 minutes for a second of sanity who I feared becoming so much I had decided I just wouldn’t have children at all. I couldn’t convince myself to sign up for that because I didn’t understand the joy and satisfaction that comes with motherhood even among those circumstances. So we sacrificed a lot, more than I know how to explain, and it was totally worth it. You can read more about that [here]().

This is what the actual birth was like:

After much deliberation on where to give birth, the island or the city, we chose to rent an apartment in Panama City for two weeks for the home birth.We were finally settled into the well lit, cozy, 3 bedroom apartment in Albrook Neighborhood of Panama City, Panama.My baby would be the 8th baby born in this apartment.The owner of the apartment was a very sweet and welcoming Jewish lady who actually lived overseas but used the apartment when visiting her son and his family in Panama.Her son’s two children had been born here and then they had rented it out to friends who needed a place to give birth in the city.Home births are currently a rare thing in Panama.My parents and a friend flew down and were staying in the apartment with us for the birth and beginning of the newborn phase.

I woke up the morning of July 2, 2015 at 6am with contractions.I felt birth was coming very soon.I lost more of the mucous plug in the bathroom.I went to the living room and my Dad was there, I gave him a hug.I checked email and facebook and looked up some info about GBS and mucous plugs.I had tested positive for GBS and was really concerned about it.I realized I could not focus on my computer and it was because contractions were too intense and I realized this could be labor.I sensed I needed to spend this time with Nathaniel.I went back to bed where he was still sleeping, we cuddled, we made love and breathed through each contraction together.I learned this technique from Ina May Gaskin.We would look right into each other’s eyes, breathing together through the contraction as it would rise and fall like a wave.It made all the difference.Instead of feeling pain, my body would relax and I would feel the sensation of the womb tightening and squeezing and then I would feel it relax.I felt in love and connected and safe.I tried breathing through a few contractions, or rushes as Ina May calls them, alone.I really had to self connect.I enjoyed trying both but preferred breathing through them with Nathaniel the most.I made sure to connect and breathe with each person in the house.Everyone’s presence at the birth matters.On a primal level, our bodies and our biology are seeking information that we are safe in every sense of the word, to open up, putting ourselves and our baby in a vulnerable position.I wanted to feel safe with everyone present.

I sat on the balcony with Dad and we breathed through a few contractions together.He got teary eyed each time.He was reading his 1611 Bible.He asked me what the contractions felt like.I explained that for me they started in my back wrapped abound to the front, low abdomen.It was intense, but not necessarily painful.The eye contact and the breathing totally changed the sensation.Joab came out and we breathed through one together, his eyes looked curious and excited.He also asked how they felt and I told him.Dad or Joab would tell Nathaniel each time I told them one was starting or finishing.Nathaniel was finishing my playlist in our room.I kept wondering if this could really be it.It felt too easy.

Mom made us delicious breakfast tacos.I loved having her there to cook and take care of us.She and I breathed through one contraction together.She didn't know what to do with all that eye contact. I knew she would get into it though. At this point the energy started shifting into a more focused time. I was starting to believe this was tthe day baby would come and I wanted to enjoy it and be intentional with every choice. Everything felt real and surreal all at once. I went to the bathroom and labored on the toilet for a bit. Nathaniel was timing everything. We were at 6 min apart. Dr Aybar was coming in an hour and a half. Nathaniel was downloading my playlist. I was welcoming every sensation, relaxing and breathing into it, telling my womb and my vagina they could open so big, the baby could come now. I was quiet and self connected.

Nathaniel and I stayed in the room rush by rush we breathed together.I sat in the birth ball in the corner of the room and I will would hang from his neck through a rush encouraging baby to move down.He was strong and safe and sexy, creating stability and security for me to stay in my birth flow.Mom brought me grapes and Nana’s hot sauce dip and chips.I moved to the bed and laid down to rest.I loved having everyone around.I felt grounded and happy.The rushes kept getting closer but I still couldn’t believe this could be labor! There was no pain, it wasn't scary, it didn't seem intense enough.Dr.Aybar arrived.I was on the toilet and he just popped his head in the bathroom which really surprised me! If I was further along in labor it wouldn't have cared at all but I felt slightly embarrassed at this stage! Then I thought, well it’s about to all be out there anyway! I came out to the bed and he checked me. Everyone was in the room and I felt a little vulnerable. He taught Nathaniel how to check me too. Nathaniel’s touch felt better and more comfortable for me, naturally. Then he said I was at a 6 or a 7 and I felt so, so happy I didn’t care about anything else! I was relieved and ecstatic to have someone confirm this was really it! This was labor and it was going as beautiful as I had hoped it would. I was inspired, empowered and optimistic.

I walked around the living room and the house.Dr.Aybar and the family were in the living room.He said he thought the baby would come at 6. I said maybe 4, just kidding around.I asked Nathaniel to come back to the room with me to focus on the brith.I was feeling distracted in the living room.In the room I sat on the birth ball in the corner.Nathaniel moved from the chair in front of me to the bed, back and forth.Always there when I needed him.To kiss through a rush or hang from his neck through one.Nathaniel and I listened to one of Alan Watts’ lectures about Being Born.I sat in the corner on the birth ball and he was on the bed and he and I just stared into each others eyes and cried through the rushes, little happy tears, it was our baby’s turn to be born into the oneness of the Universe, that is all of us.

Mom came in and she and I used eye contact through a few rushes and it felt steady and safe.Dad and I also and he teared up and said, ‘you’re doing that.’ The back labor started getting intense and I started wanting the birth tub.The baby felt so low and like her head would come out anytime.I didn’t want to miss out on the birth tub because she came too fast.I got in the shower and let the hot water hit my back as I sat on the birth ball facing the wall.Every time I called it a birth ball Nathaniel would say, ‘It’s a swedish exercise ball.’ Nathaniel told Dr.Aybar to start the birth tub, he did though he thought it was too soon.I had to come check the water temperature twice, even walking 10 feet from the bathroom to the birth tub felt hard, I stood waiting in my towel then my sarong for the tub to fill up.Hanging on Nathaniel and kissing through rushes.Things were starting to get heavy.

My memories become a little blurred together with very vivid highlights at this point.During the whole birth Nahko & Medicine for the People had been playing.My favorite song from the playlist was the slow version of Aloha Ke Akua.

The birth tub was finally ready and slipping into that warm water was a huge relief.The pool was big and hanging over the edge and kissing Nathaniel through each rush was all I could do.I was feeling very introverted.Noises and words felt far away.My dad made some joke with Joab and I found their presence distracting.It started getting so intense I asked everyone but Nathaniel to leave.Dr.Aybar said he thought that was a good idea, he went and sat in the hallway and everyone else moved to the living room.

The back pain kept getting more and more intense and I started feeling like I was losing it.I remember hearing the door open and close.It was Graciela quietly coming in and sitting on the floor next to Dr.Aybar.The back labor felt different than the front, it felt like injury pain and it was scary.The front was bearable and unalarming.Dr.Aybar massaged my back during a few contractions and that helped.I realized I needed to ask for support if I needed it.The thought I hadn’t occurred to me previously.My mom peeked her head in the door.I said she could come in.I didn’t need her there for support in that moment but wanted her there for inclusion of the experience.It was a gift for me to share the experience with her.The back labor kept picking up and I was feeling scared and overwhelmed.When I world verbalize that everyone would say, ‘No! You’re not scared! You’re doing great! Scared of what ? !’ Nathaniel said, ‘I hear that you are scared and overwhelmed, ’ looking right into my eyes and I felt heard and touched and safe.Someone knew how I was actually feeling, scared, really really scared! Even now I feel overwhelmed with gratitude for the empathy and support he gave me and how competent he is and was in that moment.I was freaking out more and more, doubting my bodies ability to handle the pain.I was crying saying, ‘I can’t do this, I’m not good at it.’ I felt so sad and so disappointed in myself for feeling those feelings and having those thoughts.

The scariest moment was not when I thought I would die, but when I was so scared and the back labor hurt so much, I didn’t care what happened to the baby or to me.I just wanted it to stop.I asked Graciela, ‘Are there drugs if I need them ?’ ‘No.No drugs, ’ she said sternly with lots of eye contact, ‘only you can do this Kadi.’ this stage lasted about 4 hours in my mind.I asked Nathaniel how long it was after the birth and he said it was about 15 minutes.This was the transition stage.

I got out of the birth tub and went to the bathroom.I felt scared to push.It hurt my back and the desire to push didn’t feel strong enough to listen to.Nathaniel would stand in front of the toilet with his arms against the wall behind me.I would sit on the toilet with my arms around his neck, hanging down.I remember being scared of the pain at this point.I crawled down on all fours on the bathroom floor.I felt betrayed - scared and alone.I had the thought everyone lied to me and didn’t tell me about this part of birth.Dr.Aybar was talking and I remember thinking, ‘words, stupid words, all Ina May’s words are stupid!’

Then I got back on the toilet and started pushing and moaning.Nathaniel said, ‘All is Well, ’ and I just said it over and over, quickly and frantically at first, ‘All is Well All is Well All is Well.’ It started as a plea and became a mantra.I started feeling the urge to push and I did.I moaned from deep down.I felt her moving down and it felt satisfying.The fear was starting to disperse.

Now things were easier, the back labor was over and I knew I had to push the baby out no matter what.It was time to get back in the birth tub, baby felt so close.I crouched in a squat in the warm water.I was pushing and moaning and totally in my body.Dr.Aybar would ask, ‘can you feel the head ?’ I could.It was inspiring.Then he had me lean back so he could feel.He said it was close.Nathaniel was in the birth tub with me now, sitting behind me.I had asked if he could get in, Dr.Aybar said, ‘Whatever you want!’ Nathaniel had been massaging my back through every contraction - he was hinged over at the waist leaning over the edge of the tub.I knew it would be easier if he was just in the water and I could lean back against his chest between contractions and if felt so comforting.

Baby was almost here, everyone was gathered around, Dr.Aybar had asked Joab and Dad to come back in.I was so glad he did that, I was to in the moment to care who else was there or if there were photos.I reached down and I felt that the baby had hair and I felt so happy! I imagined the baby with hair and feeling it made the baby so real to me.I told the baby we could do this, to come on out.I was squatting in the water with my hands down holding my vagina and massaging my clitoris as the ring of fire began.This helped me.stay relax and open slowly.I thought I tore because I heard and felt a pop, but it didn't hurt. I didn't actually tear though, I think it was actually my water breaking.

    Dr.Aybar would say, ‘push, push.’ But I would only consider it and listen to my body.If it wanted to push I would, if not, I wouldn’t.I did not want to tear.I felt tuned in and in control.I would push and then pant letting her recede and come out nice and slow.I looked down and saw the GoPro underwater and corrected its position to film the birth.I felt her head coming out and it felt so good! She was almost here and I was enjoying pushing so much more than the transition phase!

I finally felt I was open enough to push her head out.It came out and her body wriggled out soon after.I’ll never forget her dark hair and her open eyes looking at me from under water.I was in awe - the most surreal and real moment of my life! She wiggled out and I brought her up to my bare stomach, we just stared at each other as we leaned back against Nathaniel’s chest and he looked over my shoulder.She was so tranquil and beautiful.She looked up at us, the sun was coming in strong through the window.Everything looked golden and beautiful, especially her.Someone asked if it was a boy or a girl, I reached down and lifted one of her legs, ‘It’s a girl!!!’ I cried of happiness and leaned my head on Nathaniel’s shoulder.I felt so happy.This moment was so perfect, in the water with our daughter, her umbilical cord was a little short but very strong, it pumped for almost half an hour.It truly was the golden hour.

    Dr.Aybar mentioned pushing when I felt a contraction and I told him I was trying not to think about that - everyone laughed.He said you know what Ina May says about the placenta - in unison we said, ‘It doesn’t have bones!’ I pushed a tiny bit and the placenta was out! I was so relieved! Nathaniel cut the cord with a small razor blade.I held her against my chest.

Graciela asked me to hand her to Nathaniel if I felt like I could shower.I was surprised I felt so good.I got up, climbed over the edge of the tub and went to shower.I was freezing! The hot water kept coming and going in the shower which was very unpleasant.Graciela said it was time to get out.I waited for one more hot water spell.I climbed into bed and Nathaniel gave me the baby and he went to shower.We were just there with her for rest of the night.I didn’t sleep at all.I just stared at her and cuddled her and fed her all night.
